name: studio-nuxt-build
run-name: Studio Nuxt Build

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [20]

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js with Corepack
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      # Step 3: Cache Dependencies
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # Step 4: Install Dependencies
      - name: Install Dependencies
        run: pnpm install

      # Step 5: Build the Application
      - name: Build the Application
        run: pnpm build --preset github_pages
        env:
          NUXT_PUBLIC_STUDIO_API_URL: https://api.nuxt.studio

      # Step 6: Deploy to gh-pages
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./.output/public

  sync-gh-pages-to-master:
    needs: build-and-deploy
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout gh-pages Branch
      - name: Checkout gh-pages Branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      # Step 2: Configure Git
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      # Step 3: Merge gh-pages into Master
      - name: Merge gh-pages into Master
        run: |
          git fetch origin
          git checkout master
          git merge --no-ff gh-pages -m "Automated merge from gh-pages to master"
          git push origin master
